name: Run Telegram Config Scraper

on:
  schedule:
    # اجرای خودکار راس هر ساعت رند
    - cron: '0 * * * *'
  workflow_dispatch:
    # امکان اجرای دستی از تب Actions

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon pycryptodome

      - name: Run Scraper Script
        env:
          # سکرت‌های شما که در تنظیمات ریپازیتوری ذخیره شده است
          TELEGRAM_API_ID: ${{ secrets.TG_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TG_API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TG_SESSION_STRING }}
        run: python scraper.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # اضافه کردن فایل‌های خروجی و دیتابیس آیدی‌ها به گیت
          git add configs.txt channel_ids.json
          
          # بررسی اینکه آیا تغییری ایجاد شده است یا خیر
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update collected configs and ID cache [Automated]" && git push)


concurrency:
  group: telethon-bot
  cancel-in-progress: true
